language: node_js

before_install:
  - npm install -g npm
  - npm --version || echo npm not installed
  - node --version || echo node not installed
  - echo "package version $PACKAGE_VERSION"

stages:
  - install
  - test
  - build
  - storybook
  - release

jobs:
  include:
    # Job: Install
    - stage: install
      node_js:
        - 'lts/*'
        - '10'
        - '8'
      script:
        - travis_retry npm install

    # Job: Test
    - stage: test
      node_js:
        - 'lts/*'
        - '10'
        - '8'
      script:
        - npm run test

    # Job: Build
    - stage: build
      node_js:
        - 'lts/*'
        - '10'
        - '8'
      script:
        - npm run build

    # Job: Storybook
    - stage: storybook
      node_js:
        - 'lts/*'
        - '10'
        - '8'
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build-storybook

    # Job: Release
    - stage: release
      script: ls
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release